services:
  sportfest-app:
    build: .
    container_name: sportfest-app
    restart: unless-stopped
    ports:
      - "8500:8500"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./VERSION:/app/VERSION
      - ./CHANGELOG.md:/app/CHANGELOG.md
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8500
      --reload